### ISSUE TITLE
Version Update in backend

### ISSUE THREAD

**Issue by manishdashsharma** [LL07-Team-Dowell/100098-DowellJobPortal#1]
1. All the URLS are having post request , change those POST to GET where it is required for fetching data from database .
2. Use thread in all the APIs .
3. Optimize the APIs .

**Comment by UMAIR271** [comment]
@Hardik0812 in weekend 
can you change those POST to GET where it is required for fetching data from database?

**Comment by Hardik0812** [comment]
> @Hardik0812 in weekend can you change those POST to GET where it is required for fetching data from database?

yes sure

**Comment by manishdashsharma** [comment]
This is not urgent requirements .
Another requirement :
1. Refactor the code base , one app folder . @Hardik0812 @UMAIR271

**Comment by UMAIR271** [comment]
ok

**Comment by Hardik0812** [comment]
@manishdashsharma do we need to refactor code in only one app. If yes then it might be difficult to find the code we are looking for and the code file will be soo big  as well as the migration might change if we kept all model in one folder then.
Please explain me what should be the next step.

**Comment by manishdashsharma** [comment]
> @manishdashsharma do we need to refactor code in only one app. If yes then it might be difficult to find the code we are looking for and the code file will be soo big as well as the migration might change if we kept all model in one folder then. Please explain me what should be the next step.

1. Candidate Management 
2. HR Management
3. Lead Management
4. Account Management 
5. Research Management
6. Task Management
7. Training Management

Can be in one app 
Setting we will ne different
